DROP DATABASE IF EXISTS NEWS_READER;

CREATE DATABASE NEWS_READER;

USE NEWS_READER;

CREATE TABLE FEED (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(1023),
	url VARCHAR(1023),
	lastModifiedTime BIGINT(20),
	lastCrawledTime BIGINT(20),
	isEnabled SMALLINT
) ENGINE=MyISAM DEFAULT CHARSET=utf8 MAX_ROWS=100000;

CREATE TABLE CATEGORY (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(1023)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 MAX_ROWS=100000;

CREATE TABLE NEWS (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	feedId INT UNSIGNED NOT NULL,
	guidValue VARCHAR(1023),
	title VARCHAR(1023),
	baseUri VARCHAR(1023),
	feedLink VARCHAR(1023),
	author VARCHAR(255),
	updatedTime BIGINT(20),
	publishedTime BIGINT(20),
	content TEXT,
	description TEXT,
	INDEX (feedId)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 MAX_ROWS=1000000000;

CREATE TABLE EXPERIOS (
	newsId INT UNSIGNED NOT NULL PRIMARY KEY,
        feedId INT UNSIGNED NOT Null,
	json TEXT,
	update_time BIGINT(20),
	INDEX(feedId)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 MAX_ROWS=1000000000;
